---
# tasks file for mytomcat
-  inculde-tasks: installjava.yml
-  inculde-tasks: createtomcatuser.yml
-  inculde-tasks: installtomcat.yml
-  inculde-tasks: updatepermissions.yml
-  inculde-tasks: tomcatservice.yml
-  inculde-tasks: starttomcat.yml


