---
# tasks file for mytomact
- include_tasks: installjava.yml
- include_tasks: createtomcatuser.yml
- include_tasks: installtomcat.yml
- include_tasks: updatepermissions.yml
- include_tasks: tomcatservice.yml





